FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend

# 👇 Add these two lines
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

RUN bun install


RUN apt-get update -y && apt-get install -y openssl


RUN bun run generate:db

EXPOSE 8080

CMD ["bun", "run", "start:backend"]
